/** 用户侧工具与配置：内置 CDP/邮箱实例 + 个人外部 MCP，全部复用现有接口。 */
import React, { useCallback, useState } from 'react';
import { Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { createBuiltinInstance, createMyMcpService, deleteBuiltinInstance, deleteMyMcpService, getBuiltinIntegration, listBuiltinInstances, listMyMcpServices, syncMyMcpService, updateBuiltinInstance, updateMyMcpService, type BuiltinIntegration, type BuiltinToolInstance, type MyMcpService, type ToolKind } from '@/api/resources';
import { AdminSheet, CodeBlock, FilterBar, LabeledInput, SectionCard, SwitchRow } from '@/components/admin-ui';
import { BigTitle, EmptyView, GlassNav, LoadingView } from '@/components/ui';
import { spacing, useTheme } from '@/theme';

const TABS = [{ value: 'builtin', label: '内置工具' }, { value: 'mcp', label: '外部 MCP' }] as const;
type Tab = (typeof TABS)[number]['value'];

export default function ResourcesScreen() {
  const t = useTheme(); const router = useRouter();
  const [tab, setTab] = useState<Tab>('builtin'); const [instances, setInstances] = useState<BuiltinToolInstance[]>([]); const [services, setServices] = useState<MyMcpService[]>([]); const [integrations, setIntegrations] = useState<Partial<Record<ToolKind, BuiltinIntegration>>>({});
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [instanceKind, setInstanceKind] = useState<ToolKind | null>(null); const [instanceName, setInstanceName] = useState('');
  const [mcpEdit, setMcpEdit] = useState<MyMcpService | null | undefined>(undefined); const [mName, setMName] = useState(''); const [mDisplay, setMDisplay] = useState(''); const [mDesc, setMDesc] = useState(''); const [mUrl, setMUrl] = useState(''); const [mToken, setMToken] = useState(''); const [mHeaders, setMHeaders] = useState(''); const [mEnabled, setMEnabled] = useState(true);

  const load = useCallback(async () => { setError(''); try { const [i, m, cdp, mail] = await Promise.all([listBuiltinInstances(), listMyMcpServices(), getBuiltinIntegration('cdp').catch(() => undefined), getBuiltinIntegration('mail').catch(() => undefined)]); setInstances(i); setServices(m); setIntegrations({ cdp, mail }); } catch (e) { setError((e as Error)?.message || '加载失败'); } finally { setLoading(false); } }, []);
  React.useEffect(() => { void load(); }, [load]);
  const addInstance = async () => { if (!instanceKind || !instanceName.trim()) return; setBusy(true); try { await createBuiltinInstance({ tool_kind: instanceKind, name: instanceName.trim(), enabled: true }); setInstanceKind(null); await load(); } catch (e) { Alert.alert('创建失败', (e as Error)?.message || '请稍后重试'); } finally { setBusy(false); } };
  const openMcp = (svc?: MyMcpService) => { setMcpEdit(svc ?? null); setMName(svc?.name || ''); setMDisplay(svc?.display_name || ''); setMDesc(svc?.description || ''); setMUrl(svc?.url || ''); setMToken(''); setMHeaders(''); setMEnabled(svc?.enabled ?? true); };
  const saveMcp = async () => { if (!mName.trim() || !mUrl.trim()) return; let headers: Record<string, string> = {}; try { headers = mHeaders.trim() ? JSON.parse(mHeaders) : {}; } catch { Alert.alert('Headers 必须是 JSON 对象'); return; } setBusy(true); try { const body = { display_name: mDisplay.trim(), description: mDesc.trim(), url: mUrl.trim(), enabled: mEnabled, headers, ...(mToken.trim() ? { token: mToken.trim() } : {}) }; if (mcpEdit) await updateMyMcpService(mcpEdit.id, body); else await createMyMcpService({ ...body, name: mName.trim(), url: mUrl.trim() }); setMcpEdit(undefined); await load(); } catch (e) { Alert.alert('保存失败', (e as Error)?.message || '请稍后重试'); } finally { setBusy(false); } };
  if (loading) return <View style={{ flex: 1, backgroundColor: t.bg }}><LoadingView label="加载工具与配置…" /><GlassNav title="工具与配置" onBack={() => router.back()} /></View>;
  return <><View style={{ flex: 1, backgroundColor: t.bg }}><ScrollView contentContainerStyle={{ paddingTop: spacing.pad + 48, paddingHorizontal: spacing.pad, paddingBottom: 50, gap: 12 }}><BigTitle title="工具与配置" sub="管理内置工具实例及个人外部 MCP" /><FilterBar value={tab} options={TABS} onChange={setTab} />{error ? <EmptyView title="加载失败" subtitle={error} icon="alert" /> : tab === 'builtin' ? <>
    {(['cdp', 'mail'] as ToolKind[]).map((kind) => <SectionCard key={kind} title={kind === 'cdp' ? '浏览器 CDP' : '邮箱'}><Text style={{ color: t.tx3, fontSize: 11.5, lineHeight: 17 }}>{integrations[kind]?.description || (kind === 'cdp' ? '通过浏览器扩展连接网页会话。' : '管理邮箱账户、地址和邮件工具。')}</Text>{instances.filter((x) => x.tool_kind === kind).map((x) => <View key={x.id} style={{ paddingVertical: 9, borderTopWidth: 0.5, borderColor: t.line }}><View style={{ flexDirection: 'row', alignItems: 'center' }}><Text style={{ flex: 1, color: t.tx, fontWeight: '700' }}>{x.name}</Text><SwitchRow label="启用" value={x.enabled} onValueChange={(v) => void updateBuiltinInstance(x.id, { enabled: v }).then(load)} /></View><View style={{ flexDirection: 'row', gap: 15 }}><Pressable onPress={() => router.push({ pathname: '/resources/[id]', params: { id: String(x.id), kind: x.tool_kind, name: x.name } } as never)}><Text style={{ color: t.acTx, fontWeight: '700', fontSize: 12 }}>配置详情</Text></Pressable><Pressable onPress={() => Alert.alert('删除实例', `删除“${x.name}”？`, [{ text: '取消' }, { text: '删除', style: 'destructive', onPress: () => void deleteBuiltinInstance(x.id).then(load) }])}><Text style={{ color: t.red, fontWeight: '700', fontSize: 12 }}>删除</Text></Pressable></View></View>)}<Pressable onPress={() => { setInstanceKind(kind); setInstanceName(''); }} style={{ paddingVertical: 8 }}><Text style={{ color: t.acTx, fontWeight: '700' }}>＋ 新增{kind === 'cdp' ? '浏览器' : '邮箱'}实例</Text></Pressable></SectionCard>)}
  </> : <><Pressable onPress={() => openMcp()} style={{ height: 44, borderRadius: 14, backgroundColor: t.ac, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: '#fff', fontWeight: '700' }}>新增外部 MCP</Text></Pressable><SectionCard title={`MCP 服务 (${services.length})`}>{services.map((s) => <View key={s.id} style={{ paddingVertical: 10, borderBottomWidth: 0.5, borderColor: t.line }}><View style={{ flexDirection: 'row' }}><View style={{ flex: 1 }}><Text style={{ color: t.tx, fontWeight: '700' }}>{s.display_name || s.name}</Text><Text style={{ color: t.tx3, fontSize: 11, marginTop: 3 }}>{s.url}</Text><Text style={{ color: s.runtime_status === 'error' ? t.red : t.tx3, fontSize: 10.5, marginTop: 3 }}>{s.runtime_status || '未同步'} · {s.tool_count || 0} 个工具</Text></View><SwitchRow label="启用" value={s.enabled} onValueChange={(v) => void updateMyMcpService(s.id, { enabled: v }).then(load)} /></View><View style={{ flexDirection: 'row', gap: 15, marginTop: 7 }}><Pressable onPress={() => openMcp(s)}><Text style={{ color: t.acTx, fontWeight: '700', fontSize: 12 }}>编辑</Text></Pressable><Pressable onPress={() => void syncMyMcpService(s.id).then((r) => { Alert.alert(r.ok ? '同步完成' : '同步失败', r.ok ? `发现 ${r.tool_count || 0} 个工具` : r.error || '未知错误'); return load(); })}><Text style={{ color: t.acTx, fontWeight: '700', fontSize: 12 }}>同步</Text></Pressable><Pressable onPress={() => Alert.alert('删除 MCP', `删除“${s.display_name || s.name}”？`, [{ text: '取消' }, { text: '删除', style: 'destructive', onPress: () => void deleteMyMcpService(s.id).then(load) }])}><Text style={{ color: t.red, fontWeight: '700', fontSize: 12 }}>删除</Text></Pressable></View>{s.tools?.length ? <CodeBlock text={s.tools.map((x) => x.name).join('\n')} /> : null}</View>)}</SectionCard></> }</ScrollView><GlassNav title="工具与配置" onBack={() => router.back()} /></View>
  <AdminSheet visible={!!instanceKind} title="新增内置工具实例" onClose={() => setInstanceKind(null)} submitLabel="创建" onSubmit={addInstance} submitting={busy}><LabeledInput label="类型" value={instanceKind === 'cdp' ? '浏览器 CDP' : '邮箱'} onChangeText={() => undefined} disabled /><LabeledInput label="实例名称" value={instanceName} onChangeText={setInstanceName} /></AdminSheet>
  <AdminSheet visible={mcpEdit !== undefined} title={mcpEdit ? '编辑 MCP 服务' : '新增 MCP 服务'} onClose={() => setMcpEdit(undefined)} submitLabel="保存" onSubmit={saveMcp} submitting={busy}><LabeledInput label="名称" value={mName} onChangeText={setMName} disabled={!!mcpEdit} /><LabeledInput label="显示名" value={mDisplay} onChangeText={setMDisplay} /><LabeledInput label="描述" value={mDesc} onChangeText={setMDesc} multiline /><LabeledInput label="SSE URL" value={mUrl} onChangeText={setMUrl} autoCapitalize="none" /><LabeledInput label="Bearer Token" value={mToken} onChangeText={setMToken} secureTextEntry hint={mcpEdit ? '留空保留现有 Token' : '可选'} /><LabeledInput label="自定义 Headers JSON" value={mHeaders} onChangeText={setMHeaders} multiline autoCapitalize="none" /><SwitchRow label="启用" value={mEnabled} onValueChange={setMEnabled} /></AdminSheet>
  </>;
}
